/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


    class AppTest {
        String inputFilePath = "./app/src/main/resources/a.bmp";
        String outputFilePath = "./app/src/main/resources/";
        String grayFile = "a.bmp";
        Bitmap testFile = new Bitmap(inputFilePath, outputFilePath, grayFile);
        @Test
        @DisplayName("testing the reading")
        public void testReadFile() {
            assertEquals(testFile.readFile(),true,"File not found");
        }
        @Test
        @DisplayName("testing the saving")
        public void testSaveFile() {
            testFile.readFile();
            assertEquals(testFile.saveFile(),true,"File not saved");
        }
        @Test
        @DisplayName("testing the Black and white")
        public void BlackAndWhite() {
            testFile.readFile();
            assertEquals(testFile.BlackAndWhite(),true);
        }
        @Test
        @DisplayName("testing the imageFlipVertical")
        public void imageFlipVertical() {
            testFile.readFile();
            int lastRGBVal = -10123362;
            assertEquals(testFile.imageFlipVertical(),lastRGBVal,"File not flipped horizontally");
        }

    }

